[package]
name = "wechat-dump"
version = "0.1.0"
authors = ["Jiajie Chen <c@jia.je>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sqlx = { version = "0.5.1", features = [ "sqlite", "runtime-async-std-native-tls" ] }
async-std = { version = "1.9.0", features = [ "attributes" ] }
anyhow = "1.0.38"
clap = "2.33.3"
roxmltree = "0.14.0"
chrono = "0.4.19"
